/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ControlesBusqueda: typeof import('./src/components/ControlesBusqueda.vue')['default']
    LibroDiccionario: typeof import('./src/components/LibroDiccionario.vue')['default']
    ResultadosBusqueda: typeof import('./src/components/ResultadosBusqueda.vue')['default']
  }
}
